databases:
  - name: start_your_day_right
    databaseName: start_your_day_right_4o4d
    user: erika
    region: singapore

services:
  - type: web
    name: start_your_day_right
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: start_your_day_right
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
