phrases = [
  { english_text: "You have to believe in yourself when no one else does.", japanese_text: "誰一人信じなくともあなたがあなた自身を信じなくちゃ。" },
  { english_text: "When you have a dream, you've got to grab it and never let go.", japanese_text: "夢があるなら、掴みとって絶対に離さないこと。" },
  { english_text: "It's gonna be an amazing day today!", japanese_text: "今日は最高の日になるよ！" },
  { english_text: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", japanese_text: "笑って。人生は美しいもので、あなたを笑顔にするものがたくさんあるから。"},
  { english_text: "Be persistent and never give up hope.", japanese_text: "粘り強く、希望を決して捨てないでいて。"},
  { english_text: "Always do your best. What you plant now, you will harvest later.", japanese_text: "いつも最善を尽くすこと。今植えた種は、後で大きな収穫になるから。"},
  { english_text: "The only person you are destined to become is the person you decide to be.", japanese_text: "あなたがこれからどんな人間になるかは、あなた自身が決めること。"},
  { english_text: "You are enough just as you are.", japanese_text: "あなたはそのままのあなたで十分なんだよ。"},
  { english_text: "Believe in yourself", japanese_text: "自分自身を信じて。"},
  { english_text: "Step outside your comfort zone and try new things to grow.", japanese_text: "自分にとって居心地の良い領域から飛び出し、新しいことに挑んで成長しよう。"},
  { english_text: "Be a dreamer and a doer.", japanese_text: "夢を持ってそれを実現する人になろう。"},
  { english_text: "The harder you work for something, the greater you'll feel when you achieve it.", japanese_text: "何かに向かって頑張れば頑張るほど、達成した時の喜びは大きい。"},
  { english_text: "Don't stop when you're tired. Stop when you're done.", japanese_text: "疲れたときに止まるんじゃない。達成した時にだけ止まるんだ。"},
  { english_text: "Wake up with determination. Go to bed with satisfaction.", japanese_text: "やる気と共に目覚め、満足感と共に眠りにつこう。"},
  { english_text: "Do something today that your future self will thank you for.", japanese_text: "未来の自分に感謝されるようなことを今日しよう。"},
  { english_text: "It's going to be hard, but hard does not mean impossible.", japanese_text: "険しい道のりであってもそれは不可能ではない。"},
  { english_text: "Don't wait for opportunity. Create it.", japanese_text: "チャンスを待たないで。作り出そう。"},
  { english_text: "Dream it. Believe it. Build it.", japanese_text: "夢をもって。信じて。実現しよう。"},
  { english_text: "No masterpiece was ever created by a lazy artist.", japanese_text: "どんな傑作も怠慢なアーティストからは生まれていない。"},
  { english_text: "You'll never know everything about anything.", japanese_text: "何かを完全に理解することは決してできないよ。"},
  { english_text: "You don't learn to walk by following rules. You learn by doing, and by falling over.", japanese_text: "赤ん坊はルールを守りながら歩き方を学ぶわけじゃない。挑戦して、失敗しながら学ぶんだ。"},
  { english_text: "The sky is the limit.", japanese_text: "限界なんてないよ。"},
  { english_text: "Keep pushing. I know you can do it.", japanese_text: "頑張って。あなたならできる。"},
  { english_text: "Don't start tomorrow. Start today.", japanese_text: "明日からじゃなくて今日やろう。"},
  { english_text: "Smile. You are beautiful as you are.", japanese_text: "笑って。あなたはそのままで素敵だよ。"},
  { english_text: "Everything is gonna be alright. Don't worry anything.", japanese_text: "全てうまくいくよ。何も心配しないで。"},
  { english_text: "Good job for waking up today. You are doing great already!", japanese_text: "起きられてえらい。あなたは既にがんばってる！"},
  { english_text: "You do not need to compare yourself to other people. It's always you vs you.", japanese_text: "自分を他と比べる必要なんてない。いつも自分対自分。"},
  { english_text: "If you need to rest, just rest. It's okay to rest.", japanese_text: "休養が必要なら休みなさい。休んだっていいんだよ。"},
  { english_text: "Did you know that you're loved?", japanese_text: "あなたは愛されているって知ってた？"},
  { english_text: "Don't be busy making a living that you forget to make a life. Slow down and enjoy each day.", japanese_text: "生活に追われて人生を楽しむことを忘れないで。立ち止まって、1日1日を楽しもう。"},
  { english_text: "You only get to live once. Make it special.", japanese_text: "人生は一度きり。特別なものにしよう。"},
  { english_text: "Don't give up without even trying.", japanese_text: "挑戦する前にあきらめないで。"},
  { english_text: "You may not have the result you want today or tomorrow, but eventually, YOU WILL WIN.", japanese_text: "求めている結果は今日や明日じゃ手に入らないかもしれない。でもいつかはきっと、それを勝ち取ることができるよ。"},
  { english_text: "Just be yourself. You're perfect.", japanese_text: "自分らしくいて。あなたは完璧なんだから。"},
  { english_text: "Be strong. Be kind. Be yourself.", japanese_text: "強く、優しく、自分らしくいて。"},
  { english_text: "Don't live in the past. Make today wonderful.", japanese_text: "過去に生きるな。今日を素晴らしいものにしよう。"},
  { english_text: "A younger version of you is looking at you now, in proud disbelief of who you have grown into.", japanese_text: "過去のあなたが今のあなたをみたら、その成長っぷりに驚いて、誇りに思うだろう。"},
  { english_text: "Look how far you've come. Don't give up now.", japanese_text: "あなたが歩んできた道のりの長さをみてごらんよ。今諦めないで。"},
  { english_text: "You don't need to be someone else. Just be yourself, you are beautiful inside out.", japanese_text: "他の誰かになろうとしなくていいんだよ。あなた自身のままでいて。あなたは中身から全て美しい。"},
  { english_text: "Nothing is impossible.", japanese_text: "不可能なことなんてない。"},
  { english_text: "You are never too old to dream a new dream.", japanese_text: "新しい夢を持つのに歳なんて関係ないさ。"},
  { english_text: "You are working so hard everyday.", japanese_text: "毎日がんばってるね。"},
  { english_text: "Just don't give up trying to do what you really want to do. ", japanese_text: "本当にやりたいことに向かって挑戦することを諦めないで。"},
  { english_text: "Do not compare yourself to someone else. Compare yourself to who you were yesterday.", japanese_text: "自分自身を他の誰かと比べるんじゃない。今日の自分を昨日の自分と比べるんだ。"},
  { english_text: "It always seems impossible until it's done.", japanese_text: "何事もやり遂げるまでは不可能に思えるものさ。"},
  { english_text: "Never allow a person to tell you that you can't.", japanese_text: "他人に「あなたにはできない」なんて言わせるな。"},
  { english_text: "Keep it up! You are doing fantastic!", japanese_text: "そのまま進め！あなたは十分頑張ってる！"},
  { english_text: "A problem is a chance for you to be stronger.", japanese_text: "ピンチは自分自身を強くするチャンスだよ。"},
  { english_text: "Love yourself first.", japanese_text: "まず自分自身を愛しなさい。"},
  { english_text: "Consistency is the key to success", japanese_text: "成功の鍵は継続すること。"},
  { english_text: "Happiness is not by chance, but by choice.", japanese_text: "幸せは偶然掴むものじゃなく、選択して掴むもの。"},
  { english_text: "If you start something new, do not stop it until it's done.", japanese_text: "新しいことを始めたのなら、やり切るまで止まるんじゃない。"},
  { english_text: "Your limitation—it's only your imagination.", japanese_text: "限界ーそれはあなたがただ想像しているだけ。"},
  { english_text: "Push yourself, because no one else is going to do it for you.", japanese_text: "自分で自分を奮い立たせろ。他の誰もやってはくれないよ。"},
  { english_text: "Sometimes later becomes never. Do it now.", japanese_text: "たまに「後でやる」は「一生やらない」ことになる。だから「今」やろう。"},
  { english_text: "When you feel like quitting think about why you started.", japanese_text: "やめようかと思える時は、どうして始めたのか考えてみよう。"},
  { english_text: "The first step to getting anywhere is deciding you're no longer willing to stay where you are.", japanese_text: "何かを成し遂げるための最初の一歩は、現状を変える決断をすること。"},
  { english_text: "Just stick with it. What seems so hard now will one day be your warm up.", japanese_text: "ただ粘り強くいよう。今難しく思えることはいつかあなたにとって準備運動に過ぎないと感じるものとなる。"},
  { english_text: "Everybody wants happiness, nobody wants pain, but you can't have a rainbow without a little rain.", japanese_text: "誰しもが幸せを求め、誰も痛みを求めない。でも雨なしで虹は見られないものさ。"},
  { english_text: "If you don't sacrifice for what you want, what you want becomes the sacrifice.", japanese_text: "自分の成し遂げたいことのために犠牲を払えないのなら、成し遂げたいことそのものが犠牲となるだろう。"},
  { english_text: "Next time you think of beautiful things, don't forget to count yourself in.", japanese_text: "次に美しいものについて考える時、自分自身を含めることを忘れないで。"},
  { english_text: "The pain you feel today is the strength you'll feel tomorrow.", japanese_text: "今日の痛みは、明日の強みになる。"},
  { english_text: "Slow progress is better than no progress.", japanese_text: "ゆっくりとでも前進することは、少しも進まないことよりずっといい。"},
  { english_text: "Ask yourself if what you're doing today will get you closer to where you want to be tomorrow.", japanese_text: "今日自分がしていることで明日の自分が辿り着きたい場所に近づけられるのかを自分自身に聞いてみよう。"},
  { english_text: "Your value doesn't decrease based on someone's inability to see your worth.", japanese_text: "あなたの価値を見抜く力のない人がいても、あなたの本当の価値がなくなるわけじゃないよ。"},
  { english_text: "If you want a different result, make a different choice.", japanese_text: "異なる結果が欲しいなら、異なる選択をしよう。"},
  { english_text: "Keep your face to the sunshine and you cannot see a shadow.", japanese_text: "いつも明るい方を向いていれば、影なんて見えないさ。"},
  { english_text: "Once you replace negative thoughts with positive ones, you'll start having positive results.", japanese_text: "否定的な考えを肯定的なものに変えられたら、肯定的な結果を得られるだろう。"},
  { english_text: "Life is better when you are laughing.", japanese_text: "笑っている時の方が人生は豊かになるよ。"},
  { english_text: "You must take action. You must do the impossible. Because giving up is never an option.", japanese_text: "行動しなさい。不可能なことをやりなさい。諦めるという選択肢はないんだから。"},
  { english_text: "Stop and listen to yourself. Do what your heart wants you to do.", japanese_text: "立ち止まって自分の声を聞いて。自分の心が求めていることをやろう。"},
  { english_text: "I have no doubt that your persistence will lead you to great success.", japanese_text: "あなたの粘り強く続ける力は必ずあなたを成功へと導いてくれるよ。"},
  { english_text: "You're doing an incredible job, and I believe in you!", japanese_text: "あなたはとっても頑張ってる。あなたならできるって信じてる！"},
  { english_text: "You inspire others with your positivity and determination.", japanese_text: "あなたのポジティブさと頑張りは他の人にもいい影響を与えているよ。"}
]

# それぞれのフレーズをデータベースに追加
phrases.each do |phrase|
  Phrase.create!(phrase)
end
